version: '3.30'

services:
  mysql:
    image: mysql:latest
    container_name: database_container
    environment:
      MYSQL_DATABASE: 'blog'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - webapi_network  
  redis:
    image: redis:latest
    container_name: redis_container
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - redis:/etc/redis
    ports:
      - "6379:6379"
    networks:
      - webapi_network


volumes:
  mysql:
  redis:
networks:
  webapi_network:
    driver: bridge 