version: '3.30'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: 'blog'
      POSTGRES_PASSWORD: 'rootPassword'
      POSTGRES_USER: user
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - webapi_network
    
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - redis:/etc/redis
    ports:
      - "6379:6379"
    networks:
      - webapi_network


volumes:
  postgres:
  redis:
networks:
  webapi_network:
    driver: bridge 