server:
  port: 8000
postgres:
  port: 5432
  host: 127.0.0.1
  username: user
  password: password
  db_name: blog
jwt:
  secret: mysecretkey
redis:
  port: 6379
  host: 127.0.0.1
  username: ""
  password: ""
  db:       0
  protocol: 3
logger:
  log_file_path: ../logs/log.log   
  logger_name: zap
  level: debug
  encoding: json