server:
  Port: 8090
mysql:
  Port: 3306
  Host: 0.0.0.0
  Username: root
  Password: password
  DBname: blog
  ParseTime: true
jwt:
  Secret: mysecretkey
redis:
  Port: 6379
  Host: 0.0.0.0
  Username: ""
  Password: ""
  DBname:       0
  Protocol: 3